### ISSUE TITLE
Floodgate downloads

### ISSUE THREAD

**Issue by dragonexagon** [ShiftOS/ShiftOS#16]
System.IO.DirectoryNotFoundException' in mscorlib.dll

it can't find 'C:\ShiftOSShiftum42\Drivers\HDD.dri'.

**Comment by rezedus** [comment]
`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ShiftOSShiftum42\Drivers\HDD.dri'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at ShiftOS.FloodGate_Manager.successinfo(String item)
   at ShiftOS.FloodGate_Manager.tmrdwnld_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`
This one?

**Comment by rezedus** [comment]
https://github.com/ShiftOS/ShiftOS/blob/master/ShiftOS/FloodGate%20Manager.vb#L543-L547
